server/config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions

  resources :pals

  resources :audiences

  resources :environments

  resources :emotions

  resources :posts

  get 'home/index'
  get 'home/generate'
  get 'user/:id', :to => 'users#show'
  get 'user/:id/alerts', :to => 'alerts#user', :as => :user_alerts
  get 'posts/since/:id', :to => 'posts#since'
  
  scope :format => true, :contrains => { :format => 'json' } do
    post 'posts/create', :to => 'posts#create_mobile'
    
    devise_scope :user do
      post 'users', :to => 'user/registrations#create_mobile'
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :sessions => 'user/sessions'
  }
  
  
  root :to => "home#index"

end

server/app/models/environment.rb
class Environment < ActiveRecord::Base
  
  belongs_to :post
  
  validates_presence_of :post
  validates_presence_of :sensor
  validates_presence_of :reading
  
  AMBIENT_TEMPERATURE = "Ambient Temperature" # Celsius
  LIGHT               = "Light"               # Lux
  PRESSURE            = "Pressure"            # Millibars
  RELATIVE_HUMIDITY   = "Relative Humidity"   # %
  
  ALL = [
    AMBIENT_TEMPERATURE,
    LIGHT,
    PRESSURE,
    RELATIVE_HUMIDITY
  ]
  
end

server/app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @environments = Environment.all
    respond_with(@environments)
  end

  def show
    respond_with(@environment)
  end

  def new
    @environment = Environment.new
    respond_with(@environment)
  end

  def edit
  end

  def create
    @environment = Environment.new(environment_params)
    @environment.save
    respond_with(@environment)
  end

  def update
    @environment.update(environment_params)
    respond_with(@environment)
  end

  def destroy
    @environment.destroy
    respond_with(@environment)
  end

  private
    def set_environment
      @environment = Environment.find(params[:id])
    end

    def environment_params
      params.require(:environment).permit(:type, :reading, :post_id)
    end
end

server/app/helpers/environments_helper.rb
module EnvironmentsHelper
end

server/app/views/environments/_environment.html.erb
<p><strong><%= environment.sensor %></strong> <%= environment.reading %></p>

server/app/views/environments/_form.html.erb
<%= form_for(@environment) do |f| %>
  <% if @environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% @environment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :reading %><br>
    <%= f.text_field :reading %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/environments/edit.html.erb
<h1>Editing environment</h1>

<%= render 'form' %>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', environments_path %>

server/app/views/environments/index.html.erb
<h1>Environments</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Type</th>
      <th>Reading</th>
      <th>Post</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @environments.each do |environment| %>
      <tr>
        <td><%= environment.sensor %></td>
        <td><%= environment.reading %></td>
        <td><%= environment.post.text %></td>
        <td><%= link_to 'Show', environment %></td>
        <td><%= link_to 'Edit', edit_environment_path(environment) %></td>
        <td><%= link_to 'Destroy', environment, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Environment', new_environment_path %>

server/app/views/environments/new.html.erb
<h1>New environment</h1>

<%= render 'form' %>

<%= link_to 'Back', environments_path %>

server/app/views/environments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @environment.type %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @environment.reading %>
</p>

<p>
  <strong>Post:</strong>
  <%= @environment.post_id %>
</p>

<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %>