server/config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions

  resources :pals

  resources :audiences

  resources :environments

  resources :emotions

  resources :posts

  get 'home/index'
  get 'home/generate'
  get 'user/:id', :to => 'users#show'
  get 'user/:id/alerts', :to => 'alerts#user', :as => :user_alerts
  get 'posts/since/:id', :to => 'posts#since'
  
  scope :format => true, :contrains => { :format => 'json' } do
    post 'posts/create', :to => 'posts#create_mobile'
    
    devise_scope :user do
      post 'users', :to => 'user/registrations#create_mobile'
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :sessions => 'user/sessions'
  }
  
  
  root :to => "home#index"

end

server/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  
  belongs_to :source,
             :class_name  => 'User',
             :foreign_key => 'source_user_id'

  belongs_to :target,
             :class_name  => 'User',
             :foreign_key => 'target_user_id'

  validates_uniqueness_of :source_user_id, :scope => :target_user_id
  
  validate :cannot_add_self
  
  private
  
  def cannot_add_self
    if source_user_id == target_user_id
      errors.add(:target_user_id, "You cannot add yourself as a friend")
    end
  end
  
end

server/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @subscriptions = Subscription.all
    respond_with(@subscriptions)
  end

  def show
    respond_with(@subscription)
  end

  def new
    @subscription = Subscription.new
    respond_with(@subscription)
  end

  def edit
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.save
    respond_with(@subscription)
  end

  def update
    @subscription.update(subscription_params)
    respond_with(@subscription)
  end

  def destroy
    @subscription.destroy
    respond_with(@subscription)
  end

  private
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def subscription_params
      params.require(:subscription).permit(:source_user_id, :target_user_id)
    end
end

server/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

server/app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_user_id %><br>
    <%= f.number_field :source_user_id %>
  </div>
  <div class="field">
    <%= f.label :target_user_id %><br>
    <%= f.number_field :target_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

server/app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Source user</th>
      <th>Target user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.source_user_id %></td>
        <td><%= subscription.target_user_id %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

server/app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

server/app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source user:</strong>
  <%= @subscription.source_user_id %>
</p>

<p>
  <strong>Target user:</strong>
  <%= @subscription.target_user_id %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>