server/config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions

  resources :pals

  resources :audiences

  resources :environments

  resources :emotions

  resources :posts

  get 'home/index'
  get 'home/generate'
  get 'user/:id', :to => 'users#show'
  get 'user/:id/alerts', :to => 'alerts#user', :as => :user_alerts
  get 'posts/since/:id', :to => 'posts#since'
  
  scope :format => true, :contrains => { :format => 'json' } do
    post 'posts/create', :to => 'posts#create_mobile'
    
    devise_scope :user do
      post 'users', :to => 'user/registrations#create_mobile'
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :sessions => 'user/sessions'
  }
  
  
  root :to => "home#index"

end

server/app/models/pal.rb
class Pal < ActiveRecord::Base
  
  belongs_to :source,
             :class_name  => 'User',
             :foreign_key => 'source_user_id'

  belongs_to :target,
             :class_name  => 'User',
             :foreign_key => 'target_user_id'

  validates_uniqueness_of :source_user_id, :scope => :target_user_id
  
  validate :cannot_add_self
  
  def self.generate
    Pal.create :source => User.random, :target => User.random
  end
  
  private
  
  def cannot_add_self
    if source_user_id == target_user_id
      errors.add(:target_user_id, "You cannot add yourself as a friend")
    end
  end
  
end

server/app/controllers/pals_controller.rb
class PalsController < ApplicationController
  before_action :set_pal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pals = Pal.all
    respond_with(@pals)
  end

  def show
    respond_with(@pal)
  end

  def new
    @pal = Pal.new
    respond_with(@pal)
  end

  def edit
  end

  def create
    @pal = Pal.new(pal_params)
    @pal.save
    respond_with(@pal)
  end

  def update
    @pal.update(pal_params)
    respond_with(@pal)
  end

  def destroy
    @pal.destroy
    respond_with(@pal)
  end

  private
    def set_pal
      @pal = Pal.find(params[:id])
    end

    def pal_params
      params.require(:pal).permit(:source_user_id, :target_user_id)
    end
end

server/app/helpers/pals_helper.rb
module PalsHelper
end

server/app/views/pals/_form.html.erb
<%= form_for(@pal) do |f| %>
  <% if @pal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pal.errors.count, "error") %> prohibited this pal from being saved:</h2>

      <ul>
      <% @pal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source_user_id %><br>
    <%= f.number_field :source_user_id %>
  </div>
  <div class="field">
    <%= f.label :target_user_id %><br>
    <%= f.number_field :target_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/pals/edit.html.erb
<h1>Editing pal</h1>

<%= render 'form' %>

<%= link_to 'Show', @pal %> |
<%= link_to 'Back', pals_path %>

server/app/views/pals/index.html.erb
<h1>Pals</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Source user</th>
      <th>Target user</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @pals.each do |pal| %>
      <tr>
        <td><%= pal.source.name %></td>
        <td><%= pal.target.name %></td>
        <td><%= link_to 'Show', pal %></td>
        <td><%= link_to 'Edit', edit_pal_path(pal) %></td>
        <td><%= link_to 'Destroy', pal, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Pal', new_pal_path %>

server/app/views/pals/new.html.erb
<h1>New pal</h1>

<%= render 'form' %>

<%= link_to 'Back', pals_path %>

server/app/views/pals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source user:</strong>
  <%= @pal.source_user_id %>
</p>

<p>
  <strong>Target user:</strong>
  <%= @pal.target_user_id %>
</p>

<%= link_to 'Edit', edit_pal_path(@pal) %> |
<%= link_to 'Back', pals_path %>