server/config/routes.rb
Rails.application.routes.draw do

  resources :subscriptions

  resources :pals

  resources :audiences

  resources :environments

  resources :emotions

  resources :posts

  get 'home/index'
  get 'home/generate'
  get 'user/:id', :to => 'users#show'
  get 'user/:id/alerts', :to => 'alerts#user', :as => :user_alerts
  get 'posts/since/:id', :to => 'posts#since'
  
  scope :format => true, :contrains => { :format => 'json' } do
    post 'posts/create', :to => 'posts#create_mobile'
    
    devise_scope :user do
      post 'users', :to => 'user/registrations#create_mobile'
    end
  end

  devise_for :users, :controllers => {
    :registrations => 'user/registrations',
    :sessions => 'user/sessions'
  }
  
  
  root :to => "home#index"

end

server/app/views/layouts/_login.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <div class="form-group">
    <%= f.text_field :email, :placeholder => 'Email' %>
	</div>

  <div class="form-group">
    <%= f.password_field :password, :placeholder => 'Password' %>
	</div>

  <div class="form-group">
    <%= f.check_box :remember_me %>
    <%= f.label :remember_me %>
	</div>
	
	<div class="form-group">
    <%= f.submit 'Sign in' %>
	</div>	
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

server/app/views/layouts/_profile.html.erb
<div id="profile">
  <span class="pull-left"><%= profile_image current_user %></span>
  <h1><%= current_user.name %></h1>
	
	<%= link_to user_alerts_path(current_user) do %>
	 <span class="badge"><%= current_user.alerts.count %></span>
	<% end %>
</div>

<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>User</th>
			<th>All</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Posts</th>
			<td><%= current_user.posts.length %></td>
			<td><%= Post.count %></td>
		</tr>
		<tr>
			<th>Emotions</th>
			<td><%= current_user.emotions.length %></td>
			<td><%= Emotion.count %></td>
		</tr>
		<tr>
			<th>Environments</th>
			<td><%= current_user.environments.length %></td>
			<td><%= Environment.count %></td>
		</tr>
		<tr>
			<th>Audiences</th>
			<td><%= current_user.audiences.length %></td>
			<td><%= Audience.count %></td>
		</tr>
		<tr>
			<th>Pals</th>
			<td><%= current_user.pals.length %></td>
			<td><%= Pal.count %></td>
		</tr>
	</tbody>
</table>

<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "btn btn-default navbar-btn" %>

server/app/views/layouts/_sidebar.html.erb
<div class="panel">
  <div class="panel-body">
    <% if current_user %>
		  <%= render "layouts/profile" %>
    <% else %>
	    <%= render "layouts/login" %>
    <% end %>
  </div>
</div>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Server</title>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default">
  <div class="container">
    <%= link_to image_tag("icon.png"), root_path, :class => "navbar-brand" %>
		
		<ul class="nav navbar-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
					Posts <span class="caret"/>
				</a>
				
				<ul class="dropdown-menu" role="menu">
          <li><%= link_to "Index", posts_path %></li>
					<li><%= link_to "New", new_post_path %></li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
					Users <span class="caret"/>
				</a>
				
				<ul class="dropdown-menu" role="menu">
			    <li><%= link_to "Sign In", new_user_session_path %></li>
			    <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
			    <li><%= link_to "New User", new_user_registration_path %></li>
			    <li><%= link_to "Edit User", edit_user_registration_path %></li>
				</ul>
			</li>
			<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
        	Emotes <span class="caret"/>
				</a>
        
        <ul class="dropdown-menu" role="menu">
			    <li><%= link_to "Index", emotions_path %></li>
			    <li><%= link_to "New", new_emotion_path %></li>
        </ul>
      </li>
			<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
        	Environs <span class="caret"/>
				</a>
        
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Index", environments_path %></li>
          <li><%= link_to "New", new_environment_path %></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
          Audiences <span class="caret"/>
        </a>
        
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Index", audiences_path %></li>
          <li><%= link_to "New", new_audience_path %></li>
        </ul>
      </li>
			      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">
          Pals <span class="caret"/>
        </a>
        
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Index", pals_path %></li>
          <li><%= link_to "New", new_pal_path %></li>
        </ul>
      </li>
		</ul>

		<%=
		  link_to "Generate",
              home_generate_path,
              :class => "btn btn-default navbar-btn" + (Generator.is_started? ? " active" : "")
    %>
  </div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-8">
			<p><%= notice %></p>
      <p><%= alert %></p>
      <%= yield %>
		</div>
	  <div class="col-md-4" id="sidebar">
      <%= render 'layouts/sidebar' %>
		</div>
	</div>
</div>

</body>
</html>